"""adding borders to strings

Revision ID: 27b1e68e052e
Revises: 650ba012c46f
Create Date: 2023-05-25 04:16:07.418829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b1e68e052e'
down_revision = '650ba012c46f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
